# Generated by Django 4.0.6 on 2022-07-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientweight',
            old_name='weight',
            new_name='amount',
        ),
    ]
