version: '3.3'

services:

  db:
    env_file:
      - .env
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: anismary/foodgram:v1
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    env_file:
      - ./.env

  frontend:
    image: anismary/foodgram_frontend:v1
    volumes:
      - result_build:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:var/html/backend_static/
      - media_value:var/html/backend_media/
    depends_on:
      - backend

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value:
