# Generated by Django 4.0.6 on 2022-07-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0003_alter_ingredientweight_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes_ingredients', through='recipes.IngredientWeight', to='ingredients.ingredient'),
        ),
    ]
