# Generated by Django 4.0.6 on 2022-07-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'любимый рецепт', 'verbose_name_plural': 'любимые рецепты'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки на пользовотелей'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'список покупок', 'verbose_name_plural': 'списки покупок'},
        ),
    ]
